### ISSUE TITLE
Issues with the html serializer

### ISSUE THREAD

**Issue by careyestes** [prismicio/php-symfony-starter#7]
Links in the html serializer seems to be offset when certain characters are used previous to the <a> tag.

For instance, Smart Quotes and em dashes cause the offset. 

Here is an example:
http://macp.sva.edu/blog/specimens-and-fakes-encyclopedic-collections-and-contemporary-art

The link "The Pale Fox" is incorrectly labeled, as the link is set on the end of "premiered". It does not look like this in Prismic. If I remove the em dash, it looks correct on the frontend.

**Comment by erwan** [comment]
this should be fixed now.
