### ISSUE TITLE
Composer create-project not working

### ISSUE THREAD

**Issue by robations** [prismicio/php-symfony-starter#8]
From readme.md:

> How to start?

> curl -s http://getcomposer.org/installer | php --
> php composer.phar create-project prismic/symfony-starter php-symfony-starter

`prismic/symfony-starter` isn't registered on Packagist:

https://packagist.org/packages/prismic/

So it bails out with: `[InvalidArgumentException] Could not find package prismic/symfony-starter with stability stable.`

**Comment by chartgroup** [comment]
+ 1

**Comment by erwan** [comment]
that's done
